### ISSUE TITLE
Build error /participant/profile static page generation

### ISSUE THREAD

**Issue by justin-phxm** [Code-the-Change-YYC/hackathon-management-tool#75]
Generating static pages (7/25)  [==  ]n [Error]: Dynamic server usage: Route /participant/profile couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at l (C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\.next\server\chunks\948.js:1:37247)
    at h (C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\.next\server\chunks\60.js:1:6284)
    at eY (C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\.next\server\chunks\60.js:27:18560)
    at eH (C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\.next\server\chunks\60.js:27:18176)
    at C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\.next\server\chunks\60.js:27:19560
    at p (C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\.next\server\chunks\407.js:1:22046)
    at C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\.next\server\chunks\407.js:1:22281
    at eh (C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:134786)
    at e (C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:137671)
    at ek (C:\Users\night\Desktop\CodeTheChange\hackathon-management-tool\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:138145) {
  description: "Route /participant/profile couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
  digest: 'DYNAMIC_SERVER_USAGE'
}

![image](https://github.com/user-attachments/assets/4225f186-169b-4b61-be57-9e8aa9692f46)

**Comment by ideen1** [comment]
Are you importing the server side client on a client page?

**Comment by ideen1** [comment]
I don't see this anywhere in the builds
